<ProductData>
	<ClothingAccessories>
		<VariationData>
			<Parentage>{Parentage}</Parentage>
			<Size>{Size}</Size>
			<Color>{Color}</Color>
			<VariationTheme>{VariationTheme}</VariationTheme>
		</VariationData>
		<ClassificationData>
			<Department>{Department}</Department>
			<ColorMap>{ColorMap}</ColorMap>
			<SpecialSizeType>{Department}</SpecialSizeType>
		</ClassificationData>
	</ClothingAccessories>
</ProductData>
